In [1]:
import pandas as pd
import numpy as np
import os

In [2]:
Grouped_Player_Avgs_data = os.path.join('../CleanData/Players_Avg_Stats_09_21_clean.csv')
Grouped_Player_Avgs_df = pd.read_csv(Grouped_Player_Avgs_data)
Grouped_Player_Avgs_df

,pid,GP,Min_per,Ortg,usg,eFG,TS_per,ORB_per,DRB_per,AST_per,...,pts,Drafted,Round_Drafted,Number_of_Yrs_Played,Last_Yr_in_College_Date_Yr,player_name,Last_Yr_in_College_team,Last_Yr_in_College_conf,Last_Yr_in_College_School_Yr,Last_Yr_in_College_Position
0,2,26.0,29.500000,97.3,16.600000,42.500000,44.430000,1.6,4.6,15.8,...,3.884600,0.0,0.0,1,2009,DEANDRAE ROSS,South Alabama,SB,So,Unknown
1,3,33.0,63.133333,107.4,17.233333,51.166667,53.403333,2.3,6.2,14.8,...,7.796367,0.0,0.0,3,2011,POOH WILLIAMS,Utah St.,WAC,Sr,Combo G
2,5,27.0,72.000000,96.2,21.800000,45.700000,47.980000,2.1,8.0,14.7,...,12.185200,0.0,0.0,1,2009,JESUS VERDEJO,South Florida,BE,Sr,Unknown
3,8,30.0,44.500000,97.7,16.000000,53.600000,53.690000,4.1,9.4,13.7,...,4.933300,0.0,0.0,1,2009,MIKE HORNBUCKLE,Pepperdine,WCC,Sr,Unknown
4,9,33.0,56.200000,96.5,22.000000,52.800000,54.310000,8.3,18.6,8.2,...,7.575800,0.0,0.0,1,2009,ANTHONY BROWN,Pacific,BW,Sr,Unknown
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22364,74196,8.0,3.700000,92.7,13.400000,40.000000,45.660000,7.4,21.4,17.4,...,0.625000,0.0,0.0,1,2021,ISAIAH FOLKES,Charlotte,CUSA,Fr,Wing G
22365,74203,16.0,12.900000,129.5,13.200000,67.900000,65.840000,8.5,8.5,2.4,...,2.812500,0.0,0.0,1,2021,FRANCK KEPNANG,Oregon,P12,Fr,C
22366,74213,10.0,5.900000,47.2,28.600000,11.900000,17.110000,0.0,24.9,13.8,...,1.727300,0.0,0.0,1,2021,GERALD DOAKES,New Mexico St.,WAC,Fr,Wing G
22367,74217,9.0,17.100000,86.9,21.800000,39.100000,40.090000,7.3,12.3,6.5,...,5.111100,0.0,0.0,1,2021,DAVID JONES,DePaul,BE,Fr,Wing F
22368,74218,13.0,11.000000,99.1,15.100000,60.000000,55.370000,10.2,21.2,3.8,...,2.615400,0.0,0.0,1,2021,MAC ETIENNE,UCLA,P12,Fr,C

In [3]:
Conferences_to_keep = ['ACC','SEC','B12','P12','B10','BE','MWC','P10','WCC','Amer','A10','CUSA','OVC','Horz','CAA',
                       'WAC','SB','Pat','BSky','Sum','SC','MVC','MAC','BW','MEAC','Ivy']

In [4]:
Grouped_Player_Avgs_df= Grouped_Player_Avgs_df[Grouped_Player_Avgs_df['Last_Yr_in_College_conf'].isin(Conferences_to_keep)]
Grouped_Player_Avgs_df

,pid,GP,Min_per,Ortg,usg,eFG,TS_per,ORB_per,DRB_per,AST_per,...,pts,Drafted,Round_Drafted,Number_of_Yrs_Played,Last_Yr_in_College_Date_Yr,player_name,Last_Yr_in_College_team,Last_Yr_in_College_conf,Last_Yr_in_College_School_Yr,Last_Yr_in_College_Position
0,2,26.0,29.500000,97.3,16.600000,42.500000,44.430000,1.6,4.6,15.8,...,3.884600,0.0,0.0,1,2009,DEANDRAE ROSS,South Alabama,SB,So,Unknown
1,3,33.0,63.133333,107.4,17.233333,51.166667,53.403333,2.3,6.2,14.8,...,7.796367,0.0,0.0,3,2011,POOH WILLIAMS,Utah St.,WAC,Sr,Combo G
2,5,27.0,72.000000,96.2,21.800000,45.700000,47.980000,2.1,8.0,14.7,...,12.185200,0.0,0.0,1,2009,JESUS VERDEJO,South Florida,BE,Sr,Unknown
3,8,30.0,44.500000,97.7,16.000000,53.600000,53.690000,4.1,9.4,13.7,...,4.933300,0.0,0.0,1,2009,MIKE HORNBUCKLE,Pepperdine,WCC,Sr,Unknown
4,9,33.0,56.200000,96.5,22.000000,52.800000,54.310000,8.3,18.6,8.2,...,7.575800,0.0,0.0,1,2009,ANTHONY BROWN,Pacific,BW,Sr,Unknown
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22364,74196,8.0,3.700000,92.7,13.400000,40.000000,45.660000,7.4,21.4,17.4,...,0.625000,0.0,0.0,1,2021,ISAIAH FOLKES,Charlotte,CUSA,Fr,Wing G
22365,74203,16.0,12.900000,129.5,13.200000,67.900000,65.840000,8.5,8.5,2.4,...,2.812500,0.0,0.0,1,2021,FRANCK KEPNANG,Oregon,P12,Fr,C
22366,74213,10.0,5.900000,47.2,28.600000,11.900000,17.110000,0.0,24.9,13.8,...,1.727300,0.0,0.0,1,2021,GERALD DOAKES,New Mexico St.,WAC,Fr,Wing G
22367,74217,9.0,17.100000,86.9,21.800000,39.100000,40.090000,7.3,12.3,6.5,...,5.111100,0.0,0.0,1,2021,DAVID JONES,DePaul,BE,Fr,Wing F
22368,74218,13.0,11.000000,99.1,15.100000,60.000000,55.370000,10.2,21.2,3.8,...,2.615400,0.0,0.0,1,2021,MAC ETIENNE,UCLA,P12,Fr,C

In [5]:
Grouped_Player_Avgs_df['Last_Yr_in_College_conf'].unique()

array(['SB', 'WAC', 'BE', 'WCC', 'BW', 'Horz', 'A10', 'ACC', 'SEC', 'Pat',
       'CAA', 'MVC', 'MAC', 'B12', 'CUSA', 'MEAC', 'P10', 'B10', 'SC',
       'Ivy', 'Sum', 'MWC', 'BSky', 'OVC', 'P12', 'Amer'], dtype=object)

In [6]:
drop_list = ['rimmade','rimmade+rimmiss',
            'midmade','midmade+midmiss','rimmade/(rimmade+rimmiss)',
            'midmade/(midmade+midmiss)','dunksmade','dunksmiss+dunksmade',
            'dunksmade/(dunksmade+dunksmiss)','Last_Yr_in_College_team','Last_Yr_in_College_conf']

In [7]:
Grouped_Player_Avgs_Clean = Grouped_Player_Avgs_df.drop(columns=drop_list)
Grouped_Player_Avgs_Clean

,pid,GP,Min_per,Ortg,usg,eFG,TS_per,ORB_per,DRB_per,AST_per,...,stl,blk,pts,Drafted,Round_Drafted,Number_of_Yrs_Played,Last_Yr_in_College_Date_Yr,player_name,Last_Yr_in_College_School_Yr,Last_Yr_in_College_Position
0,2,26.0,29.500000,97.3,16.600000,42.500000,44.430000,1.6,4.6,15.8,...,0.3462,0.038500,3.884600,0.0,0.0,1,2009,DEANDRAE ROSS,So,Unknown
1,3,33.0,63.133333,107.4,17.233333,51.166667,53.403333,2.3,6.2,14.8,...,0.4059,0.181667,7.796367,0.0,0.0,3,2011,POOH WILLIAMS,Sr,Combo G
2,5,27.0,72.000000,96.2,21.800000,45.700000,47.980000,2.1,8.0,14.7,...,0.4815,0.000000,12.185200,0.0,0.0,1,2009,JESUS VERDEJO,Sr,Unknown
3,8,30.0,44.500000,97.7,16.000000,53.600000,53.690000,4.1,9.4,13.7,...,0.5667,0.133300,4.933300,0.0,0.0,1,2009,MIKE HORNBUCKLE,Sr,Unknown
4,9,33.0,56.200000,96.5,22.000000,52.800000,54.310000,8.3,18.6,8.2,...,0.4545,0.333300,7.575800,0.0,0.0,1,2009,ANTHONY BROWN,Sr,Unknown
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22364,74196,8.0,3.700000,92.7,13.400000,40.000000,45.660000,7.4,21.4,17.4,...,0.0000,0.000000,0.625000,0.0,0.0,1,2021,ISAIAH FOLKES,Fr,Wing G
22365,74203,16.0,12.900000,129.5,13.200000,67.900000,65.840000,8.5,8.5,2.4,...,0.1250,1.125000,2.812500,0.0,0.0,1,2021,FRANCK KEPNANG,Fr,C
22366,74213,10.0,5.900000,47.2,28.600000,11.900000,17.110000,0.0,24.9,13.8,...,0.1818,0.000000,1.727300,0.0,0.0,1,2021,GERALD DOAKES,Fr,Wing G
22367,74217,9.0,17.100000,86.9,21.800000,39.100000,40.090000,7.3,12.3,6.5,...,0.4444,0.222200,5.111100,0.0,0.0,1,2021,DAVID JONES,Fr,Wing F
22368,74218,13.0,11.000000,99.1,15.100000,60.000000,55.370000,10.2,21.2,3.8,...,0.1538,0.153800,2.615400,0.0,0.0,1,2021,MAC ETIENNE,Fr,C

In [8]:
Grouped_Player_Avgs_Clean= Grouped_Player_Avgs_Clean[Grouped_Player_Avgs_Clean['mp'] >= 7.48]
Grouped_Player_Avgs_Clean

,pid,GP,Min_per,Ortg,usg,eFG,TS_per,ORB_per,DRB_per,AST_per,...,stl,blk,pts,Drafted,Round_Drafted,Number_of_Yrs_Played,Last_Yr_in_College_Date_Yr,player_name,Last_Yr_in_College_School_Yr,Last_Yr_in_College_Position
0,2,26.0,29.500000,97.3,16.600000,42.500000,44.430000,1.6,4.6,15.8,...,0.3462,0.038500,3.884600,0.0,0.0,1,2009,DEANDRAE ROSS,So,Unknown
1,3,33.0,63.133333,107.4,17.233333,51.166667,53.403333,2.3,6.2,14.8,...,0.4059,0.181667,7.796367,0.0,0.0,3,2011,POOH WILLIAMS,Sr,Combo G
2,5,27.0,72.000000,96.2,21.800000,45.700000,47.980000,2.1,8.0,14.7,...,0.4815,0.000000,12.185200,0.0,0.0,1,2009,JESUS VERDEJO,Sr,Unknown
3,8,30.0,44.500000,97.7,16.000000,53.600000,53.690000,4.1,9.4,13.7,...,0.5667,0.133300,4.933300,0.0,0.0,1,2009,MIKE HORNBUCKLE,Sr,Unknown
4,9,33.0,56.200000,96.5,22.000000,52.800000,54.310000,8.3,18.6,8.2,...,0.4545,0.333300,7.575800,0.0,0.0,1,2009,ANTHONY BROWN,Sr,Unknown
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22359,74187,19.0,57.800000,109.5,17.500000,59.100000,61.380000,5.9,16.2,8.8,...,0.6842,0.421100,9.894700,0.0,0.0,1,2021,MUSTAPHA AMZIL,Fr,Stretch 4
22361,74190,18.0,47.500000,67.4,20.700000,37.200000,38.000000,0.9,11.8,23.8,...,0.6842,0.000000,4.631600,0.0,0.0,1,2021,CARTER WHITT,Fr,Scoring PG
22365,74203,16.0,12.900000,129.5,13.200000,67.900000,65.840000,8.5,8.5,2.4,...,0.1250,1.125000,2.812500,0.0,0.0,1,2021,FRANCK KEPNANG,Fr,C
22367,74217,9.0,17.100000,86.9,21.800000,39.100000,40.090000,7.3,12.3,6.5,...,0.4444,0.222200,5.111100,0.0,0.0,1,2021,DAVID JONES,Fr,Wing F
22368,74218,13.0,11.000000,99.1,15.100000,60.000000,55.370000,10.2,21.2,3.8,...,0.1538,0.153800,2.615400,0.0,0.0,1,2021,MAC ETIENNE,Fr,C

In [9]:
Drafted_df = Grouped_Player_Avgs_Clean[Grouped_Player_Avgs_Clean['Drafted'] == 1]
Drafted_df

,pid,GP,Min_per,Ortg,usg,eFG,TS_per,ORB_per,DRB_per,AST_per,...,stl,blk,pts,Drafted,Round_Drafted,Number_of_Yrs_Played,Last_Yr_in_College_Date_Yr,player_name,Last_Yr_in_College_School_Yr,Last_Yr_in_College_Position
32,57,32.000000,90.033333,112.300000,29.200000,50.200000,56.323333,2.500000,10.200000,29.600000,...,1.631267,0.540700,21.005367,1.0,2.0,3,2011,CHARLES JENKINS,Sr,Scoring PG
49,91,35.500000,61.100000,111.900000,22.050000,60.000000,59.310000,11.400000,13.950000,7.100000,...,0.469800,0.777800,11.063200,1.0,2.0,2,2011,VERNON MACKLIN,Sr,C
106,193,33.000000,51.100000,89.750000,19.000000,46.550000,50.070000,9.700000,11.200000,9.000000,...,0.618850,0.586600,5.844250,1.0,2.0,2,2010,RYAN REID,Sr,C
108,197,38.000000,85.733333,113.833333,24.500000,49.900000,54.343333,8.533333,14.866667,12.566667,...,1.161467,0.717100,17.008800,1.0,2.0,3,2011,KYLE SINGLER,Sr,Wing F
109,198,36.333333,73.000000,111.600000,25.033333,49.633333,54.560000,3.500000,7.966667,21.033333,...,1.113867,0.125567,15.466467,1.0,1.0,3,2011,NOLAN SMITH,Sr,Scoring PG
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22072,73518,29.000000,47.900000,101.900000,27.500000,51.900000,52.090000,18.300000,23.800000,15.400000,...,0.793100,0.896600,9.482800,1.0,1.0,1,2021,DAY'RON SHARPE,Fr,C
22074,73524,25.000000,51.100000,108.000000,21.300000,54.000000,58.690000,11.300000,23.400000,7.500000,...,0.760000,2.600000,8.440000,1.0,1.0,1,2021,ISAIAH JACKSON,Fr,C
22143,73630,26.000000,48.900000,91.700000,25.800000,49.700000,53.480000,6.800000,25.700000,3.800000,...,0.576900,1.000000,9.346200,1.0,2.0,1,2021,GREG BROWN III,Fr,PF/C
22178,73686,27.000000,62.500000,95.200000,27.300000,47.400000,51.710000,4.800000,11.200000,21.200000,...,1.111100,0.407400,11.259300,1.0,1.0,1,2021,KEON JOHNSON,Fr,Wing G
22208,73723,25.000000,75.900000,96.400000,21.400000,40.700000,44.720000,4.700000,11.100000,11.300000,...,1.320000,0.160000,11.480000,1.0,2.0,1,2021,BRANDON BOSTON JR.,Fr,Wing G

In [10]:
Undrafted_df = Grouped_Player_Avgs_Clean[Grouped_Player_Avgs_Clean['Drafted'] == 0]
Undrafted_df

,pid,GP,Min_per,Ortg,usg,eFG,TS_per,ORB_per,DRB_per,AST_per,...,stl,blk,pts,Drafted,Round_Drafted,Number_of_Yrs_Played,Last_Yr_in_College_Date_Yr,player_name,Last_Yr_in_College_School_Yr,Last_Yr_in_College_Position
0,2,26.0,29.500000,97.3,16.600000,42.500000,44.430000,1.6,4.6,15.8,...,0.3462,0.038500,3.884600,0.0,0.0,1,2009,DEANDRAE ROSS,So,Unknown
1,3,33.0,63.133333,107.4,17.233333,51.166667,53.403333,2.3,6.2,14.8,...,0.4059,0.181667,7.796367,0.0,0.0,3,2011,POOH WILLIAMS,Sr,Combo G
2,5,27.0,72.000000,96.2,21.800000,45.700000,47.980000,2.1,8.0,14.7,...,0.4815,0.000000,12.185200,0.0,0.0,1,2009,JESUS VERDEJO,Sr,Unknown
3,8,30.0,44.500000,97.7,16.000000,53.600000,53.690000,4.1,9.4,13.7,...,0.5667,0.133300,4.933300,0.0,0.0,1,2009,MIKE HORNBUCKLE,Sr,Unknown
4,9,33.0,56.200000,96.5,22.000000,52.800000,54.310000,8.3,18.6,8.2,...,0.4545,0.333300,7.575800,0.0,0.0,1,2009,ANTHONY BROWN,Sr,Unknown
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22359,74187,19.0,57.800000,109.5,17.500000,59.100000,61.380000,5.9,16.2,8.8,...,0.6842,0.421100,9.894700,0.0,0.0,1,2021,MUSTAPHA AMZIL,Fr,Stretch 4
22361,74190,18.0,47.500000,67.4,20.700000,37.200000,38.000000,0.9,11.8,23.8,...,0.6842,0.000000,4.631600,0.0,0.0,1,2021,CARTER WHITT,Fr,Scoring PG
22365,74203,16.0,12.900000,129.5,13.200000,67.900000,65.840000,8.5,8.5,2.4,...,0.1250,1.125000,2.812500,0.0,0.0,1,2021,FRANCK KEPNANG,Fr,C
22367,74217,9.0,17.100000,86.9,21.800000,39.100000,40.090000,7.3,12.3,6.5,...,0.4444,0.222200,5.111100,0.0,0.0,1,2021,DAVID JONES,Fr,Wing F
22368,74218,13.0,11.000000,99.1,15.100000,60.000000,55.370000,10.2,21.2,3.8,...,0.1538,0.153800,2.615400,0.0,0.0,1,2021,MAC ETIENNE,Fr,C

In [11]:
Undrafted_df = Undrafted_df.sample(n=6000)
Undrafted_df

,pid,GP,Min_per,Ortg,usg,eFG,TS_per,ORB_per,DRB_per,AST_per,...,stl,blk,pts,Drafted,Round_Drafted,Number_of_Yrs_Played,Last_Yr_in_College_Date_Yr,player_name,Last_Yr_in_College_School_Yr,Last_Yr_in_College_Position
12421,36673,31.000000,49.450000,114.175000,27.825000,62.200000,64.125000,10.375000,23.575000,10.425000,...,0.236925,0.699225,12.018975,0.0,0.0,4,2018,JOCK LANDALE,Sr,C
1625,2965,27.000000,63.400000,94.700000,18.800000,49.300000,50.590000,1.600000,7.400000,20.900000,...,1.037000,0.000000,8.444400,0.0,0.0,1,2009,SPENCER LAURIE,Sr,Unknown
15704,46816,28.750000,75.125000,105.600000,17.625000,49.900000,54.862500,1.875000,8.600000,18.325000,...,0.850675,0.033825,9.898475,0.0,0.0,4,2020,TRISTON SIMPSON,Sr,Combo G
3539,9318,8.000000,15.800000,90.700000,24.400000,31.100000,40.230000,5.700000,16.100000,9.200000,...,0.250000,0.375000,8.875000,0.0,0.0,1,2009,CHOP TANG,Jr,Unknown
14610,43210,29.666667,59.633333,110.500000,19.166667,54.266667,59.646667,7.633333,16.600000,10.633333,...,0.518600,0.630633,10.413867,0.0,0.0,3,2018,MARCUS DERRICKSON,Jr,Stretch 4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9000,26151,28.000000,62.900000,107.975000,15.300000,49.275000,53.740000,1.325000,11.325000,11.075000,...,0.636450,0.235475,8.963700,0.0,0.0,4,2014,JAKE THOMAS,Sr,Combo G
20005,70447,24.000000,50.400000,89.400000,26.300000,44.400000,49.750000,2.600000,9.800000,12.100000,...,1.000000,0.166700,9.291700,0.0,0.0,1,2021,LA'MEL ROBINSON,Fr,Combo G
9834,28789,30.333333,65.000000,90.866667,27.900000,46.266667,50.260000,3.400000,14.533333,16.133333,...,0.749833,0.599867,13.143400,0.0,0.0,3,2015,TERRAN PETTEWAY,Jr,Wing G
9003,26170,29.500000,48.475000,92.625000,12.950000,39.575000,45.242500,1.925000,9.525000,28.450000,...,0.935825,0.022050,2.570600,0.0,0.0,4,2016,PETEY MCCLAIN,Sr,Scoring PG
20405,70976,25.000000,51.400000,88.600000,24.650000,44.500000,49.665000,2.250000,8.850000,16.300000,...,0.965300,0.081000,8.506950,0.0,0.0,2,2021,SHERIF KENNEY,So,Combo G

In [12]:
Undrafted_df.Last_Yr_in_College_Date_Yr.unique()

array([2018, 2009, 2020, 2021, 2019, 2010, 2014, 2017, 2015, 2011, 2016,
       2013, 2012], dtype=int64)

In [13]:
Equal_df = pd.concat([Drafted_df,Undrafted_df])
Equal_df

,pid,GP,Min_per,Ortg,usg,eFG,TS_per,ORB_per,DRB_per,AST_per,...,stl,blk,pts,Drafted,Round_Drafted,Number_of_Yrs_Played,Last_Yr_in_College_Date_Yr,player_name,Last_Yr_in_College_School_Yr,Last_Yr_in_College_Position
32,57,32.000000,90.033333,112.300000,29.200000,50.200000,56.323333,2.500000,10.200000,29.600000,...,1.631267,0.540700,21.005367,1.0,2.0,3,2011,CHARLES JENKINS,Sr,Scoring PG
49,91,35.500000,61.100000,111.900000,22.050000,60.000000,59.310000,11.400000,13.950000,7.100000,...,0.469800,0.777800,11.063200,1.0,2.0,2,2011,VERNON MACKLIN,Sr,C
106,193,33.000000,51.100000,89.750000,19.000000,46.550000,50.070000,9.700000,11.200000,9.000000,...,0.618850,0.586600,5.844250,1.0,2.0,2,2010,RYAN REID,Sr,C
108,197,38.000000,85.733333,113.833333,24.500000,49.900000,54.343333,8.533333,14.866667,12.566667,...,1.161467,0.717100,17.008800,1.0,2.0,3,2011,KYLE SINGLER,Sr,Wing F
109,198,36.333333,73.000000,111.600000,25.033333,49.633333,54.560000,3.500000,7.966667,21.033333,...,1.113867,0.125567,15.466467,1.0,1.0,3,2011,NOLAN SMITH,Sr,Scoring PG
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9000,26151,28.000000,62.900000,107.975000,15.300000,49.275000,53.740000,1.325000,11.325000,11.075000,...,0.636450,0.235475,8.963700,0.0,0.0,4,2014,JAKE THOMAS,Sr,Combo G
20005,70447,24.000000,50.400000,89.400000,26.300000,44.400000,49.750000,2.600000,9.800000,12.100000,...,1.000000,0.166700,9.291700,0.0,0.0,1,2021,LA'MEL ROBINSON,Fr,Combo G
9834,28789,30.333333,65.000000,90.866667,27.900000,46.266667,50.260000,3.400000,14.533333,16.133333,...,0.749833,0.599867,13.143400,0.0,0.0,3,2015,TERRAN PETTEWAY,Jr,Wing G
9003,26170,29.500000,48.475000,92.625000,12.950000,39.575000,45.242500,1.925000,9.525000,28.450000,...,0.935825,0.022050,2.570600,0.0,0.0,4,2016,PETEY MCCLAIN,Sr,Scoring PG
20405,70976,25.000000,51.400000,88.600000,24.650000,44.500000,49.665000,2.250000,8.850000,16.300000,...,0.965300,0.081000,8.506950,0.0,0.0,2,2021,SHERIF KENNEY,So,Combo G

In [14]:
Categorical_Columns = Equal_df.dtypes[Equal_df.dtypes == "object"].index.tolist()
Categorical_Columns

['player_name', 'Last_Yr_in_College_School_Yr', 'Last_Yr_in_College_Position']

In [15]:
Equal_df.groupby('Number_of_Yrs_Played',as_index=False)['Number_of_Yrs_Played'].count()

   Number_of_Yrs_Played
0                  1530
1                  1839
2                  1239
3                  1987
4                    31
5                     1

In [16]:
Variables_df = Equal_df
Variables_df

,pid,GP,Min_per,Ortg,usg,eFG,TS_per,ORB_per,DRB_per,AST_per,...,stl,blk,pts,Drafted,Round_Drafted,Number_of_Yrs_Played,Last_Yr_in_College_Date_Yr,player_name,Last_Yr_in_College_School_Yr,Last_Yr_in_College_Position
32,57,32.000000,90.033333,112.300000,29.200000,50.200000,56.323333,2.500000,10.200000,29.600000,...,1.631267,0.540700,21.005367,1.0,2.0,3,2011,CHARLES JENKINS,Sr,Scoring PG
49,91,35.500000,61.100000,111.900000,22.050000,60.000000,59.310000,11.400000,13.950000,7.100000,...,0.469800,0.777800,11.063200,1.0,2.0,2,2011,VERNON MACKLIN,Sr,C
106,193,33.000000,51.100000,89.750000,19.000000,46.550000,50.070000,9.700000,11.200000,9.000000,...,0.618850,0.586600,5.844250,1.0,2.0,2,2010,RYAN REID,Sr,C
108,197,38.000000,85.733333,113.833333,24.500000,49.900000,54.343333,8.533333,14.866667,12.566667,...,1.161467,0.717100,17.008800,1.0,2.0,3,2011,KYLE SINGLER,Sr,Wing F
109,198,36.333333,73.000000,111.600000,25.033333,49.633333,54.560000,3.500000,7.966667,21.033333,...,1.113867,0.125567,15.466467,1.0,1.0,3,2011,NOLAN SMITH,Sr,Scoring PG
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9000,26151,28.000000,62.900000,107.975000,15.300000,49.275000,53.740000,1.325000,11.325000,11.075000,...,0.636450,0.235475,8.963700,0.0,0.0,4,2014,JAKE THOMAS,Sr,Combo G
20005,70447,24.000000,50.400000,89.400000,26.300000,44.400000,49.750000,2.600000,9.800000,12.100000,...,1.000000,0.166700,9.291700,0.0,0.0,1,2021,LA'MEL ROBINSON,Fr,Combo G
9834,28789,30.333333,65.000000,90.866667,27.900000,46.266667,50.260000,3.400000,14.533333,16.133333,...,0.749833,0.599867,13.143400,0.0,0.0,3,2015,TERRAN PETTEWAY,Jr,Wing G
9003,26170,29.500000,48.475000,92.625000,12.950000,39.575000,45.242500,1.925000,9.525000,28.450000,...,0.935825,0.022050,2.570600,0.0,0.0,4,2016,PETEY MCCLAIN,Sr,Scoring PG
20405,70976,25.000000,51.400000,88.600000,24.650000,44.500000,49.665000,2.250000,8.850000,16.300000,...,0.965300,0.081000,8.506950,0.0,0.0,2,2021,SHERIF KENNEY,So,Combo G

In [17]:
#Drop Columns that aren't variables to predicting drafted/undrafted
Variables_df = Variables_df.drop(columns=['pid','player_name','Last_Yr_in_College_Date_Yr','pick','Drafted','Round_Drafted'])
Variables_df

,GP,Min_per,Ortg,usg,eFG,TS_per,ORB_per,DRB_per,AST_per,TO_per,...,oreb,dreb,treb,ast,stl,blk,pts,Number_of_Yrs_Played,Last_Yr_in_College_School_Yr,Last_Yr_in_College_Position
32,32.000000,90.033333,112.300000,29.200000,50.200000,56.323333,2.500000,10.200000,29.600000,16.333333,...,0.851567,3.337333,4.188933,4.326600,1.631267,0.540700,21.005367,3,Sr,Scoring PG
49,35.500000,61.100000,111.900000,22.050000,60.000000,59.310000,11.400000,13.950000,7.100000,16.950000,...,2.446350,3.007550,5.453900,0.787750,0.469800,0.777800,11.063200,2,Sr,C
106,33.000000,51.100000,89.750000,19.000000,46.550000,50.070000,9.700000,11.200000,9.000000,27.700000,...,1.678350,2.162700,3.841000,0.935950,0.618850,0.586600,5.844250,2,Sr,C
108,38.000000,85.733333,113.833333,24.500000,49.900000,54.343333,8.533333,14.866667,12.566667,14.666667,...,2.551800,4.619367,7.171167,2.142333,1.161467,0.717100,17.008800,3,Sr,Wing F
109,36.333333,73.000000,111.600000,25.033333,49.633333,54.560000,3.500000,7.966667,21.033333,17.066667,...,0.928933,2.221900,3.150833,3.271333,1.113867,0.125567,15.466467,3,Sr,Scoring PG
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9000,28.000000,62.900000,107.975000,15.300000,49.275000,53.740000,1.325000,11.325000,11.075000,14.675000,...,0.310775,2.839400,3.150150,1.580400,0.636450,0.235475,8.963700,4,Sr,Combo G
20005,24.000000,50.400000,89.400000,26.300000,44.400000,49.750000,2.600000,9.800000,12.100000,20.000000,...,0.500000,1.791700,2.291700,1.208300,1.000000,0.166700,9.291700,1,Fr,Combo G
9834,30.333333,65.000000,90.866667,27.900000,46.266667,50.260000,3.400000,14.533333,16.133333,21.466667,...,0.639633,3.298667,3.938333,1.715267,0.749833,0.599867,13.143400,3,Jr,Wing G
9003,29.500000,48.475000,92.625000,12.950000,39.575000,45.242500,1.925000,9.525000,28.450000,32.625000,...,0.353625,1.782575,2.136225,3.381550,0.935825,0.022050,2.570600,4,Sr,Scoring PG
20405,25.000000,51.400000,88.600000,24.650000,44.500000,49.665000,2.250000,8.850000,16.300000,23.900000,...,0.425900,1.625000,2.050950,1.745350,0.965300,0.081000,8.506950,2,So,Combo G

In [18]:
Categorical_Columns = Variables_df.dtypes[Variables_df.dtypes == "object"].index.tolist()
Categorical_Columns

['Last_Yr_in_College_School_Yr', 'Last_Yr_in_College_Position']

In [19]:
#Encode School_Yr
School_Yr_dict = {
    'Fr':1,
    'So':2,
    'Jr':3,
    'Sr':4
}

In [20]:
Variables_df["Last_Yr_in_College_School_Yr_Num"] = Variables_df["Last_Yr_in_College_School_Yr"].apply(lambda x: School_Yr_dict[x])
Variables_df

,GP,Min_per,Ortg,usg,eFG,TS_per,ORB_per,DRB_per,AST_per,TO_per,...,dreb,treb,ast,stl,blk,pts,Number_of_Yrs_Played,Last_Yr_in_College_School_Yr,Last_Yr_in_College_Position,Last_Yr_in_College_School_Yr_Num
32,32.000000,90.033333,112.300000,29.200000,50.200000,56.323333,2.500000,10.200000,29.600000,16.333333,...,3.337333,4.188933,4.326600,1.631267,0.540700,21.005367,3,Sr,Scoring PG,4
49,35.500000,61.100000,111.900000,22.050000,60.000000,59.310000,11.400000,13.950000,7.100000,16.950000,...,3.007550,5.453900,0.787750,0.469800,0.777800,11.063200,2,Sr,C,4
106,33.000000,51.100000,89.750000,19.000000,46.550000,50.070000,9.700000,11.200000,9.000000,27.700000,...,2.162700,3.841000,0.935950,0.618850,0.586600,5.844250,2,Sr,C,4
108,38.000000,85.733333,113.833333,24.500000,49.900000,54.343333,8.533333,14.866667,12.566667,14.666667,...,4.619367,7.171167,2.142333,1.161467,0.717100,17.008800,3,Sr,Wing F,4
109,36.333333,73.000000,111.600000,25.033333,49.633333,54.560000,3.500000,7.966667,21.033333,17.066667,...,2.221900,3.150833,3.271333,1.113867,0.125567,15.466467,3,Sr,Scoring PG,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9000,28.000000,62.900000,107.975000,15.300000,49.275000,53.740000,1.325000,11.325000,11.075000,14.675000,...,2.839400,3.150150,1.580400,0.636450,0.235475,8.963700,4,Sr,Combo G,4
20005,24.000000,50.400000,89.400000,26.300000,44.400000,49.750000,2.600000,9.800000,12.100000,20.000000,...,1.791700,2.291700,1.208300,1.000000,0.166700,9.291700,1,Fr,Combo G,1
9834,30.333333,65.000000,90.866667,27.900000,46.266667,50.260000,3.400000,14.533333,16.133333,21.466667,...,3.298667,3.938333,1.715267,0.749833,0.599867,13.143400,3,Jr,Wing G,3
9003,29.500000,48.475000,92.625000,12.950000,39.575000,45.242500,1.925000,9.525000,28.450000,32.625000,...,1.782575,2.136225,3.381550,0.935825,0.022050,2.570600,4,Sr,Scoring PG,4
20405,25.000000,51.400000,88.600000,24.650000,44.500000,49.665000,2.250000,8.850000,16.300000,23.900000,...,1.625000,2.050950,1.745350,0.965300,0.081000,8.506950,2,So,Combo G,2

In [21]:
Variables_df = Variables_df.drop(columns = ['Last_Yr_in_College_School_Yr'], axis=1)
Variables_df

,GP,Min_per,Ortg,usg,eFG,TS_per,ORB_per,DRB_per,AST_per,TO_per,...,oreb,dreb,treb,ast,stl,blk,pts,Number_of_Yrs_Played,Last_Yr_in_College_Position,Last_Yr_in_College_School_Yr_Num
32,32.000000,90.033333,112.300000,29.200000,50.200000,56.323333,2.500000,10.200000,29.600000,16.333333,...,0.851567,3.337333,4.188933,4.326600,1.631267,0.540700,21.005367,3,Scoring PG,4
49,35.500000,61.100000,111.900000,22.050000,60.000000,59.310000,11.400000,13.950000,7.100000,16.950000,...,2.446350,3.007550,5.453900,0.787750,0.469800,0.777800,11.063200,2,C,4
106,33.000000,51.100000,89.750000,19.000000,46.550000,50.070000,9.700000,11.200000,9.000000,27.700000,...,1.678350,2.162700,3.841000,0.935950,0.618850,0.586600,5.844250,2,C,4
108,38.000000,85.733333,113.833333,24.500000,49.900000,54.343333,8.533333,14.866667,12.566667,14.666667,...,2.551800,4.619367,7.171167,2.142333,1.161467,0.717100,17.008800,3,Wing F,4
109,36.333333,73.000000,111.600000,25.033333,49.633333,54.560000,3.500000,7.966667,21.033333,17.066667,...,0.928933,2.221900,3.150833,3.271333,1.113867,0.125567,15.466467,3,Scoring PG,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9000,28.000000,62.900000,107.975000,15.300000,49.275000,53.740000,1.325000,11.325000,11.075000,14.675000,...,0.310775,2.839400,3.150150,1.580400,0.636450,0.235475,8.963700,4,Combo G,4
20005,24.000000,50.400000,89.400000,26.300000,44.400000,49.750000,2.600000,9.800000,12.100000,20.000000,...,0.500000,1.791700,2.291700,1.208300,1.000000,0.166700,9.291700,1,Combo G,1
9834,30.333333,65.000000,90.866667,27.900000,46.266667,50.260000,3.400000,14.533333,16.133333,21.466667,...,0.639633,3.298667,3.938333,1.715267,0.749833,0.599867,13.143400,3,Wing G,3
9003,29.500000,48.475000,92.625000,12.950000,39.575000,45.242500,1.925000,9.525000,28.450000,32.625000,...,0.353625,1.782575,2.136225,3.381550,0.935825,0.022050,2.570600,4,Scoring PG,4
20405,25.000000,51.400000,88.600000,24.650000,44.500000,49.665000,2.250000,8.850000,16.300000,23.900000,...,0.425900,1.625000,2.050950,1.745350,0.965300,0.081000,8.506950,2,Combo G,2

In [22]:
Variables_df_cat_encoded = pd.get_dummies(Variables_df, columns=['Last_Yr_in_College_Position'])
Variables_df_cat_encoded

,GP,Min_per,Ortg,usg,eFG,TS_per,ORB_per,DRB_per,AST_per,TO_per,...,Last_Yr_in_College_School_Yr_Num,Last_Yr_in_College_Position_C,Last_Yr_in_College_Position_Combo G,Last_Yr_in_College_Position_PF/C,Last_Yr_in_College_Position_Pure PG,Last_Yr_in_College_Position_Scoring PG,Last_Yr_in_College_Position_Stretch 4,Last_Yr_in_College_Position_Unknown,Last_Yr_in_College_Position_Wing F,Last_Yr_in_College_Position_Wing G
32,32.000000,90.033333,112.300000,29.200000,50.200000,56.323333,2.500000,10.200000,29.600000,16.333333,...,4,0,0,0,0,1,0,0,0,0
49,35.500000,61.100000,111.900000,22.050000,60.000000,59.310000,11.400000,13.950000,7.100000,16.950000,...,4,1,0,0,0,0,0,0,0,0
106,33.000000,51.100000,89.750000,19.000000,46.550000,50.070000,9.700000,11.200000,9.000000,27.700000,...,4,1,0,0,0,0,0,0,0,0
108,38.000000,85.733333,113.833333,24.500000,49.900000,54.343333,8.533333,14.866667,12.566667,14.666667,...,4,0,0,0,0,0,0,0,1,0
109,36.333333,73.000000,111.600000,25.033333,49.633333,54.560000,3.500000,7.966667,21.033333,17.066667,...,4,0,0,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9000,28.000000,62.900000,107.975000,15.300000,49.275000,53.740000,1.325000,11.325000,11.075000,14.675000,...,4,0,1,0,0,0,0,0,0,0
20005,24.000000,50.400000,89.400000,26.300000,44.400000,49.750000,2.600000,9.800000,12.100000,20.000000,...,1,0,1,0,0,0,0,0,0,0
9834,30.333333,65.000000,90.866667,27.900000,46.266667,50.260000,3.400000,14.533333,16.133333,21.466667,...,3,0,0,0,0,0,0,0,0,1
9003,29.500000,48.475000,92.625000,12.950000,39.575000,45.242500,1.925000,9.525000,28.450000,32.625000,...,4,0,0,0,0,1,0,0,0,0
20405,25.000000,51.400000,88.600000,24.650000,44.500000,49.665000,2.250000,8.850000,16.300000,23.900000,...,2,0,1,0,0,0,0,0,0,0

In [23]:
Variables_df_cat_encoded = Variables_df_cat_encoded.drop(columns=['Last_Yr_in_College_Position_Unknown'])
Variables_df_cat_encoded

,GP,Min_per,Ortg,usg,eFG,TS_per,ORB_per,DRB_per,AST_per,TO_per,...,Number_of_Yrs_Played,Last_Yr_in_College_School_Yr_Num,Last_Yr_in_College_Position_C,Last_Yr_in_College_Position_Combo G,Last_Yr_in_College_Position_PF/C,Last_Yr_in_College_Position_Pure PG,Last_Yr_in_College_Position_Scoring PG,Last_Yr_in_College_Position_Stretch 4,Last_Yr_in_College_Position_Wing F,Last_Yr_in_College_Position_Wing G
32,32.000000,90.033333,112.300000,29.200000,50.200000,56.323333,2.500000,10.200000,29.600000,16.333333,...,3,4,0,0,0,0,1,0,0,0
49,35.500000,61.100000,111.900000,22.050000,60.000000,59.310000,11.400000,13.950000,7.100000,16.950000,...,2,4,1,0,0,0,0,0,0,0
106,33.000000,51.100000,89.750000,19.000000,46.550000,50.070000,9.700000,11.200000,9.000000,27.700000,...,2,4,1,0,0,0,0,0,0,0
108,38.000000,85.733333,113.833333,24.500000,49.900000,54.343333,8.533333,14.866667,12.566667,14.666667,...,3,4,0,0,0,0,0,0,1,0
109,36.333333,73.000000,111.600000,25.033333,49.633333,54.560000,3.500000,7.966667,21.033333,17.066667,...,3,4,0,0,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9000,28.000000,62.900000,107.975000,15.300000,49.275000,53.740000,1.325000,11.325000,11.075000,14.675000,...,4,4,0,1,0,0,0,0,0,0
20005,24.000000,50.400000,89.400000,26.300000,44.400000,49.750000,2.600000,9.800000,12.100000,20.000000,...,1,1,0,1,0,0,0,0,0,0
9834,30.333333,65.000000,90.866667,27.900000,46.266667,50.260000,3.400000,14.533333,16.133333,21.466667,...,3,3,0,0,0,0,0,0,0,1
9003,29.500000,48.475000,92.625000,12.950000,39.575000,45.242500,1.925000,9.525000,28.450000,32.625000,...,4,4,0,0,0,0,1,0,0,0
20405,25.000000,51.400000,88.600000,24.650000,44.500000,49.665000,2.250000,8.850000,16.300000,23.900000,...,2,2,0,1,0,0,0,0,0,0

In [24]:
Target = Equal_df['Drafted'].values
Target

array([1., 1., 1., ..., 0., 0., 0.])

In [25]:
X=Variables_df_cat_encoded
y=Target
print(len(X))
print(len(y))

6627
6627

In [26]:
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

In [27]:
# Splitting into Train and Test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=78)

In [28]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(4970, 54)
(1657, 54)
(4970,)
(1657,)

In [29]:
# Creating StandardScaler instance
scaler = StandardScaler()

In [30]:
# Fitting Standard Scaller
X_scaler = scaler.fit(X_train)

In [31]:
# Scaling data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

print(X_train_scaled.shape)
print(X_test_scaled.shape)

(4970, 54)
(1657, 54)

In [34]:
#Undersampling
#from imblearn.under_sampling import RandomUnderSampler
#ros = RandomUnderSampler(random_state=1)
#X_resampled, y_resampled = ros.fit_resample(X_train_scaled, y_train)
#print(X_resampled.shape)
#print(y_resampled.shape)

In [32]:
print(len(X_train_scaled))
print(len(y_train))

4970
4970

In [33]:
from sklearn.ensemble import RandomForestClassifier
# Create a random forest classifier.
rf_model = RandomForestClassifier(n_estimators=500, random_state=78)

In [34]:
# Fitting the model
rf_model = rf_model.fit(X_train_scaled, y_train)

In [35]:
# Making predictions using the testing data.
predictions = rf_model.predict(X_test_scaled)

In [36]:
print(predictions)

[0. 0. 0. ... 0. 0. 0.]

In [37]:
len(predictions)

1657

In [38]:
len(y_test)

1657

In [39]:
#Model Evaluation
# Calculating the confusion matrix
cm = confusion_matrix(y_test, predictions)
cm_df = pd.DataFrame(
    cm, index=["Actual 0", "Actual 1"], columns=["Predicted 0", "Predicted 1"]
)

# Calculating the accuracy score
acc_score = accuracy_score(y_test, predictions)

In [40]:
# Displaying results
print("Confusion Matrix")
display(cm_df)
print(f"Accuracy Score : {acc_score}")
print("Classification Report")
print(classification_report(y_test, predictions))

Confusion Matrix

          Predicted 0  Predicted 1
Actual 0         1467           31
Actual 1           61           98

Accuracy Score : 0.9444779722389861
Classification Report
              precision    recall  f1-score   support

         0.0       0.96      0.98      0.97      1498
         1.0       0.76      0.62      0.68       159

    accuracy                           0.94      1657
   macro avg       0.86      0.80      0.83      1657
weighted avg       0.94      0.94      0.94      1657

In [41]:
# Calculate feature importance in the Random Forest model.
importances = rf_model.feature_importances_
importances

array([0.02525165, 0.01127638, 0.01218225, 0.01230076, 0.00994438,
       0.00986705, 0.00858114, 0.00934658, 0.00981888, 0.01161713,
       0.01734782, 0.01780945, 0.00903111, 0.03058466, 0.02790594,
       0.00923157, 0.00846043, 0.00890532, 0.008899  , 0.00984101,
       0.00828105, 0.00998696, 0.00875801, 0.04528674, 0.0405732 ,
       0.01012598, 0.01492774, 0.03879696, 0.08803037, 0.04640225,
       0.05671715, 0.02911514, 0.01652761, 0.09988609, 0.01291239,
       0.03680689, 0.02184346, 0.00897155, 0.01388883, 0.01237218,
       0.00947527, 0.00990057, 0.01359713, 0.02088119, 0.00603836,
       0.04516877, 0.00053639, 0.00078967, 0.00068348, 0.00031841,
       0.00075352, 0.00098953, 0.00106672, 0.00138792])

In [42]:
# We can sort the features by their importance.
sorted(zip(rf_model.feature_importances_, X.columns), reverse=True)

[(0.09988608777837357, 'gbpm'),
 (0.08803036752099667, 'dporpag'),
 (0.0567171452198985, 'bpm'),
 (0.04640224652965359, 'stops'),
 (0.04528673580881366, 'porpag'),
 (0.04516877266669083, 'Last_Yr_in_College_School_Yr_Num'),
 (0.04057319705939619, 'adjoe'),
 (0.03879696118438748, 'adrtg'),
 (0.03680689276506366, 'ogbpm'),
 (0.030584655673747123, 'twoPM'),
 (0.0291151404765627, 'obpm'),
 (0.027905938280803507, 'twoPA'),
 (0.025251647121112553, 'GP'),
 (0.02184346413992237, 'dgbpm'),
 (0.02088119349224664, 'pts'),
 (0.017809445946091716, 'FTA'),
 (0.017347819384790405, 'FTM'),
 (0.016527612618164277, 'dbpm'),
 (0.014927741658341308, 'drtg'),
 (0.0138888251831155, 'dreb'),
 (0.013597131757210484, 'blk'),
 (0.012912392708741519, 'mp'),
 (0.012372181641363583, 'treb'),
 (0.012300764582934016, 'usg'),
 (0.012182246249109616, 'Ortg'),
 (0.011617130400317924, 'TO_per'),
 (0.011276384236380717, 'Min_per'),
 (0.010125980506464573, 'pfr'),
 (0.009986963849481308, 'ftr'),
 (0.009944383659146818, 'eFG'),
 (0.00990056837524158, 'stl'),
 (0.009867052140019194, 'TS_per'),
 (0.009841013788030636, 'blk_per'),
 (0.009818879688636978, 'AST_per'),
 (0.009475272096834745, 'ast'),
 (0.009346581957677704, 'DRB_per'),
 (0.009231569996205072, 'twoP_per'),
 (0.009031111588306513, 'FT_per'),
 (0.008971548190100065, 'oreb'),
 (0.008905322137121566, 'TPA'),
 (0.008898996814655119, 'TP_per'),
 (0.008758006000042971, 'ht'),
 (0.00858113626999783, 'ORB_per'),
 (0.008460434037402556, 'TPM'),
 (0.008281046074088243, 'stl_per'),
 (0.006038364995902214, 'Number_of_Yrs_Played'),
 (0.0013879233219061466, 'Last_Yr_in_College_Position_Wing G'),
 (0.0010667163294174908, 'Last_Yr_in_College_Position_Wing F'),
 (0.0009895339913404226, 'Last_Yr_in_College_Position_Stretch 4'),
 (0.0007896654638132839, 'Last_Yr_in_College_Position_Combo G'),
 (0.0007535205125471585, 'Last_Yr_in_College_Position_Scoring PG'),
 (0.000683480371678079, 'Last_Yr_in_College_Position_PF/C'),
 (0.0005363915180528724, 'Last_Yr_in_College_Position_C'),
 (0.0003184142416588804, 'Last_Yr_in_College_Position_Pure PG')]

In [ ]:
#BREAK

In [ ]:
#BREAK

In [86]:
#Try Certain year of players
Df_Year = Grouped_Player_Avgs_Clean[Grouped_Player_Avgs_Clean['Last_Yr_in_College_Date_Yr'] == 2020]
Df_Year

,pid,GP,Min_per,Ortg,usg,eFG,TS_per,ORB_per,DRB_per,AST_per,...,stl,blk,pts,Drafted,Round_Drafted,Number_of_Yrs_Played,Last_Yr_in_College_Date_Yr,player_name,Last_Yr_in_College_School_Yr,Last_Yr_in_College_Position
9310,27085,27.250000,54.175000,96.675,20.475000,52.775,55.425000,5.575000,15.575000,19.85,...,0.383275,0.532025,6.961275,0.0,0.0,4,2020,JOSH WARREN,Sr,Stretch 4
11176,32932,24.750000,32.975000,98.850,16.975000,57.575,56.692500,7.775000,16.325000,10.05,...,0.481200,0.562750,5.366325,0.0,0.0,4,2020,ANDRE ADAMS,Jr,C
11538,33955,25.600000,51.200000,114.740,17.260000,57.640,60.532000,2.660000,13.480000,14.54,...,0.560720,0.169720,9.574800,0.0,0.0,5,2020,JAKE TOOLSON,Sr,Combo G
11961,35307,29.333333,41.233333,116.300,17.666667,57.500,58.853333,9.733333,17.033333,6.40,...,0.420733,0.600533,6.976567,0.0,0.0,3,2020,EMMITT HOLT,Sr,Stretch 4
12213,36023,27.750000,59.275000,93.150,18.350000,45.425,52.462500,1.975000,7.400000,11.90,...,0.705000,0.018550,8.073375,0.0,0.0,4,2020,TORRY JOHNSON,Sr,Combo G
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21242,72102,20.000000,48.300000,86.700,19.200000,49.500,55.870000,3.600000,20.100000,10.90,...,0.173900,0.652200,7.217400,0.0,0.0,1,2020,KE'SEAN DAVIS,Jr,PF/C
21246,72107,23.000000,66.500000,92.600,24.100000,43.600,52.240000,3.400000,14.000000,12.70,...,0.961500,0.192300,12.192300,0.0,0.0,1,2020,ANDREW LEWIS,Jr,Wing G
21251,72114,8.000000,6.500000,92.000,20.700000,36.400,45.910000,10.700000,19.600000,10.80,...,0.000000,0.500000,3.125000,0.0,0.0,1,2020,MYRON GARDNER,Fr,PF/C
21262,72154,19.000000,12.200000,69.900,15.300000,38.100,41.340000,3.400000,7.600000,10.40,...,0.523800,0.000000,1.809500,0.0,0.0,1,2020,LEROY MOORE,Jr,Combo G
21272,72225,19.000000,21.900000,55.000,16.400000,24.500,30.600000,0.600000,7.200000,9.10,...,0.409100,0.000000,2.409100,0.0,0.0,1,2020,MICHAEL JOHNSON,Sr,Unknown

In [87]:
Variables_Df_Year = Df_Year

In [88]:
Variables_Df_Year = Variables_Df_Year.drop(columns=['pid','player_name','Last_Yr_in_College_Date_Yr','pick','Drafted','Round_Drafted'])
Variables_Df_Year

,GP,Min_per,Ortg,usg,eFG,TS_per,ORB_per,DRB_per,AST_per,TO_per,...,oreb,dreb,treb,ast,stl,blk,pts,Number_of_Yrs_Played,Last_Yr_in_College_School_Yr,Last_Yr_in_College_Position
9310,27.250000,54.175000,96.675,20.475000,52.775,55.425000,5.575000,15.575000,19.85,25.475,...,0.974975,2.962700,3.937675,2.188675,0.383275,0.532025,6.961275,4,Sr,Stretch 4
11176,24.750000,32.975000,98.850,16.975000,57.575,56.692500,7.775000,16.325000,10.05,26.050,...,1.069300,2.627575,3.696875,0.771075,0.481200,0.562750,5.366325,4,Jr,C
11538,25.600000,51.200000,114.740,17.260000,57.640,60.532000,2.660000,13.480000,14.54,17.660,...,0.511220,2.832640,3.343860,2.081420,0.560720,0.169720,9.574800,5,Sr,Combo G
11961,29.333333,41.233333,116.300,17.666667,57.500,58.853333,9.733333,17.033333,6.40,13.300,...,1.417100,2.597633,4.014733,0.600667,0.420733,0.600533,6.976567,3,Sr,Stretch 4
12213,27.750000,59.275000,93.150,18.350000,45.425,52.462500,1.975000,7.400000,11.90,23.050,...,0.484575,1.612375,2.096950,1.419025,0.705000,0.018550,8.073375,4,Sr,Combo G
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21242,20.000000,48.300000,86.700,19.200000,49.500,55.870000,3.600000,20.100000,10.90,29.300,...,0.826100,3.869600,4.695700,1.000000,0.173900,0.652200,7.217400,1,Jr,PF/C
21246,23.000000,66.500000,92.600,24.100000,43.600,52.240000,3.400000,14.000000,12.70,19.700,...,0.846200,3.192300,4.038500,1.576900,0.961500,0.192300,12.192300,1,Jr,Wing G
21251,8.000000,6.500000,92.000,20.700000,36.400,45.910000,10.700000,19.600000,10.80,22.800,...,1.000000,1.875000,2.875000,0.625000,0.000000,0.500000,3.125000,1,Fr,PF/C
21262,19.000000,12.200000,69.900,15.300000,38.100,41.340000,3.400000,7.600000,10.40,32.400,...,0.381000,0.476200,0.857100,0.571400,0.523800,0.000000,1.809500,1,Jr,Combo G
21272,19.000000,21.900000,55.000,16.400000,24.500,30.600000,0.600000,7.200000,9.10,26.100,...,0.045500,0.909100,0.954500,0.590900,0.409100,0.000000,2.409100,1,Sr,Unknown

In [89]:
#Encode School_Yr
School_Yr_dict = {
    'Fr':1,
    'So':2,
    'Jr':3,
    'Sr':4
}

In [90]:
Variables_Df_Year["Last_Yr_in_College_School_Yr_Num"] = Variables_Df_Year["Last_Yr_in_College_School_Yr"].apply(lambda x: School_Yr_dict[x])
Variables_Df_Year

,GP,Min_per,Ortg,usg,eFG,TS_per,ORB_per,DRB_per,AST_per,TO_per,...,dreb,treb,ast,stl,blk,pts,Number_of_Yrs_Played,Last_Yr_in_College_School_Yr,Last_Yr_in_College_Position,Last_Yr_in_College_School_Yr_Num
9310,27.250000,54.175000,96.675,20.475000,52.775,55.425000,5.575000,15.575000,19.85,25.475,...,2.962700,3.937675,2.188675,0.383275,0.532025,6.961275,4,Sr,Stretch 4,4
11176,24.750000,32.975000,98.850,16.975000,57.575,56.692500,7.775000,16.325000,10.05,26.050,...,2.627575,3.696875,0.771075,0.481200,0.562750,5.366325,4,Jr,C,3
11538,25.600000,51.200000,114.740,17.260000,57.640,60.532000,2.660000,13.480000,14.54,17.660,...,2.832640,3.343860,2.081420,0.560720,0.169720,9.574800,5,Sr,Combo G,4
11961,29.333333,41.233333,116.300,17.666667,57.500,58.853333,9.733333,17.033333,6.40,13.300,...,2.597633,4.014733,0.600667,0.420733,0.600533,6.976567,3,Sr,Stretch 4,4
12213,27.750000,59.275000,93.150,18.350000,45.425,52.462500,1.975000,7.400000,11.90,23.050,...,1.612375,2.096950,1.419025,0.705000,0.018550,8.073375,4,Sr,Combo G,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21242,20.000000,48.300000,86.700,19.200000,49.500,55.870000,3.600000,20.100000,10.90,29.300,...,3.869600,4.695700,1.000000,0.173900,0.652200,7.217400,1,Jr,PF/C,3
21246,23.000000,66.500000,92.600,24.100000,43.600,52.240000,3.400000,14.000000,12.70,19.700,...,3.192300,4.038500,1.576900,0.961500,0.192300,12.192300,1,Jr,Wing G,3
21251,8.000000,6.500000,92.000,20.700000,36.400,45.910000,10.700000,19.600000,10.80,22.800,...,1.875000,2.875000,0.625000,0.000000,0.500000,3.125000,1,Fr,PF/C,1
21262,19.000000,12.200000,69.900,15.300000,38.100,41.340000,3.400000,7.600000,10.40,32.400,...,0.476200,0.857100,0.571400,0.523800,0.000000,1.809500,1,Jr,Combo G,3
21272,19.000000,21.900000,55.000,16.400000,24.500,30.600000,0.600000,7.200000,9.10,26.100,...,0.909100,0.954500,0.590900,0.409100,0.000000,2.409100,1,Sr,Unknown,4

In [91]:
Variables_Df_Year = Variables_Df_Year.drop(columns = ['Last_Yr_in_College_School_Yr'], axis=1)
Variables_Df_Year

,GP,Min_per,Ortg,usg,eFG,TS_per,ORB_per,DRB_per,AST_per,TO_per,...,oreb,dreb,treb,ast,stl,blk,pts,Number_of_Yrs_Played,Last_Yr_in_College_Position,Last_Yr_in_College_School_Yr_Num
9310,27.250000,54.175000,96.675,20.475000,52.775,55.425000,5.575000,15.575000,19.85,25.475,...,0.974975,2.962700,3.937675,2.188675,0.383275,0.532025,6.961275,4,Stretch 4,4
11176,24.750000,32.975000,98.850,16.975000,57.575,56.692500,7.775000,16.325000,10.05,26.050,...,1.069300,2.627575,3.696875,0.771075,0.481200,0.562750,5.366325,4,C,3
11538,25.600000,51.200000,114.740,17.260000,57.640,60.532000,2.660000,13.480000,14.54,17.660,...,0.511220,2.832640,3.343860,2.081420,0.560720,0.169720,9.574800,5,Combo G,4
11961,29.333333,41.233333,116.300,17.666667,57.500,58.853333,9.733333,17.033333,6.40,13.300,...,1.417100,2.597633,4.014733,0.600667,0.420733,0.600533,6.976567,3,Stretch 4,4
12213,27.750000,59.275000,93.150,18.350000,45.425,52.462500,1.975000,7.400000,11.90,23.050,...,0.484575,1.612375,2.096950,1.419025,0.705000,0.018550,8.073375,4,Combo G,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21242,20.000000,48.300000,86.700,19.200000,49.500,55.870000,3.600000,20.100000,10.90,29.300,...,0.826100,3.869600,4.695700,1.000000,0.173900,0.652200,7.217400,1,PF/C,3
21246,23.000000,66.500000,92.600,24.100000,43.600,52.240000,3.400000,14.000000,12.70,19.700,...,0.846200,3.192300,4.038500,1.576900,0.961500,0.192300,12.192300,1,Wing G,3
21251,8.000000,6.500000,92.000,20.700000,36.400,45.910000,10.700000,19.600000,10.80,22.800,...,1.000000,1.875000,2.875000,0.625000,0.000000,0.500000,3.125000,1,PF/C,1
21262,19.000000,12.200000,69.900,15.300000,38.100,41.340000,3.400000,7.600000,10.40,32.400,...,0.381000,0.476200,0.857100,0.571400,0.523800,0.000000,1.809500,1,Combo G,3
21272,19.000000,21.900000,55.000,16.400000,24.500,30.600000,0.600000,7.200000,9.10,26.100,...,0.045500,0.909100,0.954500,0.590900,0.409100,0.000000,2.409100,1,Unknown,4

In [97]:
Variables_Df_Year_cat_encoded = pd.get_dummies(Variables_Df_Year, columns=['Last_Yr_in_College_Position'])
Variables_Df_Year_cat_encoded = Variables_Df_Year_cat_encoded.drop(columns=['Last_Yr_in_College_Position_Unknown'])
Variables_Df_Year_cat_encoded

,GP,Min_per,Ortg,usg,eFG,TS_per,ORB_per,DRB_per,AST_per,TO_per,...,Number_of_Yrs_Played,Last_Yr_in_College_School_Yr_Num,Last_Yr_in_College_Position_C,Last_Yr_in_College_Position_Combo G,Last_Yr_in_College_Position_PF/C,Last_Yr_in_College_Position_Pure PG,Last_Yr_in_College_Position_Scoring PG,Last_Yr_in_College_Position_Stretch 4,Last_Yr_in_College_Position_Wing F,Last_Yr_in_College_Position_Wing G
9310,27.250000,54.175000,96.675,20.475000,52.775,55.425000,5.575000,15.575000,19.85,25.475,...,4,4,0,0,0,0,0,1,0,0
11176,24.750000,32.975000,98.850,16.975000,57.575,56.692500,7.775000,16.325000,10.05,26.050,...,4,3,1,0,0,0,0,0,0,0
11538,25.600000,51.200000,114.740,17.260000,57.640,60.532000,2.660000,13.480000,14.54,17.660,...,5,4,0,1,0,0,0,0,0,0
11961,29.333333,41.233333,116.300,17.666667,57.500,58.853333,9.733333,17.033333,6.40,13.300,...,3,4,0,0,0,0,0,1,0,0
12213,27.750000,59.275000,93.150,18.350000,45.425,52.462500,1.975000,7.400000,11.90,23.050,...,4,4,0,1,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21242,20.000000,48.300000,86.700,19.200000,49.500,55.870000,3.600000,20.100000,10.90,29.300,...,1,3,0,0,1,0,0,0,0,0
21246,23.000000,66.500000,92.600,24.100000,43.600,52.240000,3.400000,14.000000,12.70,19.700,...,1,3,0,0,0,0,0,0,0,1
21251,8.000000,6.500000,92.000,20.700000,36.400,45.910000,10.700000,19.600000,10.80,22.800,...,1,1,0,0,1,0,0,0,0,0
21262,19.000000,12.200000,69.900,15.300000,38.100,41.340000,3.400000,7.600000,10.40,32.400,...,1,3,0,1,0,0,0,0,0,0
21272,19.000000,21.900000,55.000,16.400000,24.500,30.600000,0.600000,7.200000,9.10,26.100,...,1,4,0,0,0,0,0,0,0,0

In [98]:
Target_Year = Df_Year['Drafted'].values
Target_Year

array([0., 0., 0., ..., 0., 0., 0.])

In [99]:
X_Yr=Variables_Df_Year_cat_encoded
y_Yr=Target_Year
print(len(X_Yr))
print(len(y_Yr))

1143
1143

In [100]:
# Creating StandardScaler instance
scaler = StandardScaler()

# Fitting Standard Scaller
X_scaler = scaler.fit(X_Yr)

# Scaling data
X_Yr_scaled = X_scaler.transform(X_Yr)

print(X_Yr_scaled.shape)

(1143, 54)

In [101]:
# Making predictions using the testing data.
predictions_Yr = rf_model.predict(X_Yr_scaled)

print(len(predictions_Yr))
print(len(y_Yr))

1143
1143

In [102]:
#Model Evaluation
# Calculating the confusion matrix
cm = confusion_matrix(y_Yr, predictions_Yr)
cm_df = pd.DataFrame(
    cm, index=["Actual 0", "Actual 1"], columns=["Predicted 0", "Predicted 1"]
)

# Calculating the accuracy score
acc_score = accuracy_score(y_Yr, predictions_Yr)

In [103]:
# Displaying results
print("Confusion Matrix")
display(cm_df)
print(f"Accuracy Score : {acc_score}")
print("Classification Report")
print(classification_report(y_Yr, predictions_Yr))

Confusion Matrix

          Predicted 0  Predicted 1
Actual 0         1070           25
Actual 1            4           44

Accuracy Score : 0.9746281714785652
Classification Report
              precision    recall  f1-score   support

         0.0       1.00      0.98      0.99      1095
         1.0       0.64      0.92      0.75        48

    accuracy                           0.97      1143
   macro avg       0.82      0.95      0.87      1143
weighted avg       0.98      0.97      0.98      1143

In [71]:
#Create DF of Predictions vs Results
Df_Year['Actual'] = y_Yr
Df_Year['Predictions'] = predictions_Yr
Df_Year

C:\Users\tyler\anaconda3\envs\mlenv\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\tyler\anaconda3\envs\mlenv\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until

,pid,GP,Min_per,Ortg,usg,eFG,TS_per,ORB_per,DRB_per,AST_per,...,pts,Drafted,Round_Drafted,Number_of_Yrs_Played,Last_Yr_in_College_Date_Yr,player_name,Last_Yr_in_College_School_Yr,Last_Yr_in_College_Position,Actual,Predictions
8470,24412,29.50,54.250,101.300,18.075,48.225,52.3725,4.300,13.350,15.975,...,7.634850,0.0,0.0,4,2018,KAJON MACK,Sr,Combo G,0.0,0.0
8500,24504,26.25,53.900,97.925,20.125,46.125,50.9275,7.450,20.925,12.750,...,7.532450,0.0,0.0,4,2018,HANS BRASE,Sr,Stretch 4,0.0,0.0
9540,27796,26.25,24.825,103.225,14.600,43.350,49.0825,9.575,13.425,12.025,...,3.569400,0.0,0.0,4,2018,BEN CARTER,Sr,Wing F,0.0,0.0
9810,28733,32.75,40.225,115.325,16.975,62.825,60.4000,13.550,15.450,5.475,...,5.685675,0.0,0.0,4,2018,MARCUS LEE,Sr,C,0.0,0.0
9815,28746,27.00,40.175,102.025,21.050,46.350,50.9075,10.775,15.600,7.800,...,7.273000,0.0,0.0,4,2018,MIKE THOMAS,Sr,PF/C,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18063,52370,29.00,29.000,82.600,16.800,44.500,45.4200,1.800,9.100,15.000,...,3.225800,0.0,0.0,1,2018,KWEI LARTEY,Jr,Combo G,0.0,0.0
18069,52381,23.00,32.100,76.600,13.100,37.500,40.5200,0.300,7.600,13.300,...,2.375000,0.0,0.0,1,2018,JONATHAN GUEVARA,Jr,Combo G,0.0,0.0
18080,52398,24.00,22.200,86.400,10.900,30.000,36.0700,7.900,17.700,5.000,...,1.360000,0.0,0.0,1,2018,LUCAS SMITH,Jr,Stretch 4,0.0,0.0
18087,52426,20.00,35.900,98.700,26.700,45.200,49.5500,3.600,10.600,11.800,...,11.200000,0.0,0.0,1,2018,PATRELL ROGERS,Sr,Wing G,0.0,0.0
18096,52461,8.00,6.800,122.000,12.400,42.900,47.7500,16.000,19.700,5.700,...,2.125000,0.0,0.0,1,2018,RANDALL WEST,So,PF/C,0.0,0.0

In [72]:
Df_Year.to_csv('Supervised_ML_Results.csv', index=False)